# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ml_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DatasetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDatasets = channel.unary_unary(
            "/mlservice.DatasetService/ListDatasets",
            request_serializer=ml__service__pb2.Empty.SerializeToString,
            response_deserializer=ml__service__pb2.DatasetList.FromString,
            _registered_method=True,
        )
        self.UploadDataset = channel.unary_unary(
            "/mlservice.DatasetService/UploadDataset",
            request_serializer=ml__service__pb2.UploadDatasetRequest.SerializeToString,
            response_deserializer=ml__service__pb2.SimpleResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDataset = channel.unary_unary(
            "/mlservice.DatasetService/DeleteDataset",
            request_serializer=ml__service__pb2.DatasetName.SerializeToString,
            response_deserializer=ml__service__pb2.SimpleResponse.FromString,
            _registered_method=True,
        )
        self.DownloadDataset = channel.unary_unary(
            "/mlservice.DatasetService/DownloadDataset",
            request_serializer=ml__service__pb2.DatasetName.SerializeToString,
            response_deserializer=ml__service__pb2.FileContent.FromString,
            _registered_method=True,
        )


class DatasetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UploadDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DownloadDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DatasetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListDatasets": grpc.unary_unary_rpc_method_handler(
            servicer.ListDatasets,
            request_deserializer=ml__service__pb2.Empty.FromString,
            response_serializer=ml__service__pb2.DatasetList.SerializeToString,
        ),
        "UploadDataset": grpc.unary_unary_rpc_method_handler(
            servicer.UploadDataset,
            request_deserializer=ml__service__pb2.UploadDatasetRequest.FromString,
            response_serializer=ml__service__pb2.SimpleResponse.SerializeToString,
        ),
        "DeleteDataset": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDataset,
            request_deserializer=ml__service__pb2.DatasetName.FromString,
            response_serializer=ml__service__pb2.SimpleResponse.SerializeToString,
        ),
        "DownloadDataset": grpc.unary_unary_rpc_method_handler(
            servicer.DownloadDataset,
            request_deserializer=ml__service__pb2.DatasetName.FromString,
            response_serializer=ml__service__pb2.FileContent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlservice.DatasetService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mlservice.DatasetService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DatasetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDatasets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.DatasetService/ListDatasets",
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.DatasetList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UploadDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.DatasetService/UploadDataset",
            ml__service__pb2.UploadDatasetRequest.SerializeToString,
            ml__service__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.DatasetService/DeleteDataset",
            ml__service__pb2.DatasetName.SerializeToString,
            ml__service__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DownloadDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.DatasetService/DownloadDataset",
            ml__service__pb2.DatasetName.SerializeToString,
            ml__service__pb2.FileContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ModelServiceStub(object):
    """----- Модели -----"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedModels = channel.unary_unary(
            "/mlservice.ModelService/GetSupportedModels",
            request_serializer=ml__service__pb2.Empty.SerializeToString,
            response_deserializer=ml__service__pb2.ModelList.FromString,
            _registered_method=True,
        )
        self.GetTrainedModels = channel.unary_unary(
            "/mlservice.ModelService/GetTrainedModels",
            request_serializer=ml__service__pb2.Empty.SerializeToString,
            response_deserializer=ml__service__pb2.ModelList.FromString,
            _registered_method=True,
        )
        self.TrainModel = channel.unary_unary(
            "/mlservice.ModelService/TrainModel",
            request_serializer=ml__service__pb2.TrainRequest.SerializeToString,
            response_deserializer=ml__service__pb2.TrainResponse.FromString,
            _registered_method=True,
        )
        self.Predict = channel.unary_unary(
            "/mlservice.ModelService/Predict",
            request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
            response_deserializer=ml__service__pb2.PredictResponse.FromString,
            _registered_method=True,
        )
        self.DeleteModel = channel.unary_unary(
            "/mlservice.ModelService/DeleteModel",
            request_serializer=ml__service__pb2.ModelName.SerializeToString,
            response_deserializer=ml__service__pb2.SimpleResponse.FromString,
            _registered_method=True,
        )


class ModelServiceServicer(object):
    """----- Модели -----"""

    def GetSupportedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTrainedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSupportedModels": grpc.unary_unary_rpc_method_handler(
            servicer.GetSupportedModels,
            request_deserializer=ml__service__pb2.Empty.FromString,
            response_serializer=ml__service__pb2.ModelList.SerializeToString,
        ),
        "GetTrainedModels": grpc.unary_unary_rpc_method_handler(
            servicer.GetTrainedModels,
            request_deserializer=ml__service__pb2.Empty.FromString,
            response_serializer=ml__service__pb2.ModelList.SerializeToString,
        ),
        "TrainModel": grpc.unary_unary_rpc_method_handler(
            servicer.TrainModel,
            request_deserializer=ml__service__pb2.TrainRequest.FromString,
            response_serializer=ml__service__pb2.TrainResponse.SerializeToString,
        ),
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=ml__service__pb2.PredictRequest.FromString,
            response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
        ),
        "DeleteModel": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteModel,
            request_deserializer=ml__service__pb2.ModelName.FromString,
            response_serializer=ml__service__pb2.SimpleResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlservice.ModelService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("mlservice.ModelService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """----- Модели -----"""

    @staticmethod
    def GetSupportedModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.ModelService/GetSupportedModels",
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTrainedModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.ModelService/GetTrainedModels",
            ml__service__pb2.Empty.SerializeToString,
            ml__service__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TrainModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.ModelService/TrainModel",
            ml__service__pb2.TrainRequest.SerializeToString,
            ml__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.ModelService/Predict",
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.ModelService/DeleteModel",
            ml__service__pb2.ModelName.SerializeToString,
            ml__service__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
