# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "ml_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10ml_service.proto\x12\tmlservice"\x1b\n\x0b\x44\x61tasetName\x12\x0c\n\x04name\x18\x01 \x01(\t"\x07\n\x05\x45mpty"\x1e\n\x0b\x46ileContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"\x1f\n\x0b\x44\x61tasetList\x12\x10\n\x08\x64\x61tasets\x18\x01 \x03(\t"5\n\x14UploadDatasetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c"1\n\x0eSimpleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t"\x1b\n\tModelList\x12\x0e\n\x06models\x18\x01 \x03(\t"\x19\n\tModelName\x12\x0c\n\x04name\x18\x01 \x01(\t"f\n\x0cTrainRequest\x12\x13\n\x0bmodel_class\x18\x01 \x01(\t\x12!\n\x01X\x18\x02 \x03(\x0b\x32\x16.mlservice.FeatureList\x12\t\n\x01y\x18\x03 \x03(\x02\x12\x13\n\x0bparams_json\x18\x04 \x01(\t"?\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t"\x1d\n\x0b\x46\x65\x61tureList\x12\x0e\n\x06values\x18\x01 \x03(\x02"G\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12!\n\x01X\x18\x02 \x03(\x0b\x32\x16.mlservice.FeatureList"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\x32\x9e\x02\n\x0e\x44\x61tasetService\x12\x38\n\x0cListDatasets\x12\x10.mlservice.Empty\x1a\x16.mlservice.DatasetList\x12K\n\rUploadDataset\x12\x1f.mlservice.UploadDatasetRequest\x1a\x19.mlservice.SimpleResponse\x12\x42\n\rDeleteDataset\x12\x16.mlservice.DatasetName\x1a\x19.mlservice.SimpleResponse\x12\x41\n\x0f\x44ownloadDataset\x12\x16.mlservice.DatasetName\x1a\x16.mlservice.FileContent2\xcb\x02\n\x0cModelService\x12<\n\x12GetSupportedModels\x12\x10.mlservice.Empty\x1a\x14.mlservice.ModelList\x12:\n\x10GetTrainedModels\x12\x10.mlservice.Empty\x1a\x14.mlservice.ModelList\x12?\n\nTrainModel\x12\x17.mlservice.TrainRequest\x1a\x18.mlservice.TrainResponse\x12@\n\x07Predict\x12\x19.mlservice.PredictRequest\x1a\x1a.mlservice.PredictResponse\x12>\n\x0b\x44\x65leteModel\x12\x14.mlservice.ModelName\x1a\x19.mlservice.SimpleResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ml_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATASETNAME"]._serialized_start = 31
    _globals["_DATASETNAME"]._serialized_end = 58
    _globals["_EMPTY"]._serialized_start = 60
    _globals["_EMPTY"]._serialized_end = 67
    _globals["_FILECONTENT"]._serialized_start = 69
    _globals["_FILECONTENT"]._serialized_end = 99
    _globals["_DATASETLIST"]._serialized_start = 101
    _globals["_DATASETLIST"]._serialized_end = 132
    _globals["_UPLOADDATASETREQUEST"]._serialized_start = 134
    _globals["_UPLOADDATASETREQUEST"]._serialized_end = 187
    _globals["_SIMPLERESPONSE"]._serialized_start = 189
    _globals["_SIMPLERESPONSE"]._serialized_end = 238
    _globals["_MODELLIST"]._serialized_start = 240
    _globals["_MODELLIST"]._serialized_end = 267
    _globals["_MODELNAME"]._serialized_start = 269
    _globals["_MODELNAME"]._serialized_end = 294
    _globals["_TRAINREQUEST"]._serialized_start = 296
    _globals["_TRAINREQUEST"]._serialized_end = 398
    _globals["_TRAINRESPONSE"]._serialized_start = 400
    _globals["_TRAINRESPONSE"]._serialized_end = 463
    _globals["_FEATURELIST"]._serialized_start = 465
    _globals["_FEATURELIST"]._serialized_end = 494
    _globals["_PREDICTREQUEST"]._serialized_start = 496
    _globals["_PREDICTREQUEST"]._serialized_end = 567
    _globals["_PREDICTRESPONSE"]._serialized_start = 569
    _globals["_PREDICTRESPONSE"]._serialized_end = 607
    _globals["_DATASETSERVICE"]._serialized_start = 610
    _globals["_DATASETSERVICE"]._serialized_end = 896
    _globals["_MODELSERVICE"]._serialized_start = 899
    _globals["_MODELSERVICE"]._serialized_end = 1230
# @@protoc_insertion_point(module_scope)
